### PR TITLE
Bake component

### PR DESCRIPTION
**Pull request by seghier**
Bake component added

### CODE REVIEW

**Review by paireks — COMMENTED** [review]
Hey, BakeElement looks ok, I will change some details maybe, but could you please remove other changes in other files (25 files changed) and pull request only BakeElement.cs, Resources.resx, dotbimGH.csproj and logo? It will help me to make sure nothing else changed this way :)

**Comment by seghier** [comment]
Hi, sorry i didn't change anything but here the cs file of the component

[BakeElement.zip](https://github.com/paireks/dotbimGH/files/12589008/BakeElement.zip)

and this is the icon used or you use your own icon 🙂

bakebim

**Comment by paireks** [comment]
I can copy-paste it myself, but then your contribution will disappear :) What you can do is:
1. clone repo master branch once again
2. copy paste only what is necessary
3. create new pull request

**Comment by seghier** [comment]
> 

Ok i will do that, thanks

**Pull request closed without merging**
